## Домашняя работа по теме №2: "Матрицы и матричные операции"

### Часть 1

__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    

__Решение:__

Для того, чтобы выполнялось произведение матриц, необходимо, чтобы число столбцов первой матрицы равнялось числу строк второй. Исходя из этого:

а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;

матрица $AB$ и $BA$ не определены

б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;

матрица $AB$ определена, её размерность $2\times 3$, $BA$ - не определена

в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;

матрица $AB$ определена, её размерность $8\times 8$,  $BA$ - также определена, её размерность $3\times 3$

г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$

матрица $AB$ определена, её размерность $4\times 4$,  $BA$ - также определена, её размерность $4\times 4$

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение:__

$A+B = \begin{pmatrix} 
 1+4 & -2+(-1)\\ 
 3+0 & 0+5
\end{pmatrix} = \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

In [1]:
import numpy as np

In [2]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
A+B

array([[ 5, -3],
       [ 3,  5]])

$A \cdot B = \begin{pmatrix} 
 1 \cdot 4 + (-2) \cdot 0 & 1 \cdot (-1) + (-2) \cdot 5\\ 
 3 \cdot 4 + 0 \cdot 0 & 3 \cdot (-1) + 0 \cdot 5
\end{pmatrix} = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [3]:
np.dot(A, B)

array([[  4, -11],
       [ 12,  -3]])

$B \cdot A = \begin{pmatrix} 
 4 \cdot 1 + (-1) \cdot 3 & 4 \cdot (-2) + (-1) \cdot 0\\ 
 0 \cdot 1 + 5 \cdot 3 & 0 \cdot (-2) + 5 \cdot 2
\end{pmatrix} = \begin{pmatrix}
1 & -8\\ 
15 & 10
\end{pmatrix}$

In [4]:
np.dot(B, A)

array([[ 1, -8],
       [15,  0]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение:__

$3A = \begin{pmatrix} 
 3 \cdot 1 & 3 \cdot 7 \\ 
 3 \cdot 3 & 3 \cdot (-6)
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$

$-2B = \begin{pmatrix} 
 -2 \cdot 0 & -2 \cdot 5 \\ 
 -2 \cdot 2 & -2 \cdot (-1)
\end{pmatrix} = \begin{pmatrix}
0 & -10 \\ 
-4 & 2
\end{pmatrix}$

$4C = \begin{pmatrix} 
 4 \cdot 2 & 4 \cdot (-4) \\ 
 4 \cdot 1 & 4 \cdot 1
\end{pmatrix} = \begin{pmatrix}
8 & -16 \\ 
4 & 4
\end{pmatrix}$

$3A-2B+4C = \begin{pmatrix} 
 3+0+8 & 21-10-16 \\ 
 9-4+4 & -18+2+4
\end{pmatrix} = \begin{pmatrix}
11 & -5 \\ 
9 & -12
\end{pmatrix}$

In [5]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
np.dot(3, A) - np.dot(2, B) + np.dot(4, C)

array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

__Решение:__

$A^{T}= \begin{pmatrix}
4 & 5 & 2 \\ 
1 & -2 & 3
\end{pmatrix}$

$A \cdot A^{T} = \begin{pmatrix}
4 \cdot 4 + 1 \cdot 1 & 4 \cdot 5 + 1 \cdot (-2) & 4 \cdot 2 + 1 \cdot 3 \\ 
5 \cdot 4 + (-2) \cdot 1 & 5 \cdot 5 + (-2) \cdot (-2) & 5 \cdot 2 + (-2) \cdot 3 \\ 
2 \cdot 4 + 3 \cdot 1 & 2 \cdot 5 + 3 \cdot (-2) & 2 \cdot 2 + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13
\end{pmatrix}$

In [6]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A_t = np.transpose(A)
A_t

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [7]:
np.dot(A, A_t)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

$A^{T} \cdot A = \begin{pmatrix}
4 \cdot 4 + 5 \cdot 5 + 2 \cdot 2 & 4 \cdot 1 + 5 \cdot (-2) + 2 \cdot 3\\ 
1 \cdot 4 + (-2) \cdot 5 + 3 \cdot 2 & 1 \cdot 1 + (-2) \cdot (-2) + 3 \cdot 3
\end{pmatrix} = \begin{pmatrix}
45 & 0\\ 
0 & 14
\end{pmatrix}$

In [8]:
np.dot(A_t, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

__Решение:__

In [9]:
def matrix_compication(a, b):
    n1 = len(a)
    m1 = len(a[0])
    n2 = len(b)
    m2 = len(b[0])
    sum_elem = 0
    temporary_matrix = []
    final_matrix = []
    if m1 == n2:
        for k in range(m1):
            for j in range(n2):
                for i in range(n1):
                      sum_elem = sum_elem + a[k][i]*b[i][j]
                temporary_matrix.append(sum_elem)
                sum_elem = 0
            final_matrix.append(temporary_matrix)
            temporary_matrix = []
        return final_matrix
    else:
        print('Матрицы не могут быть перемножены, так как число столбцов первой матрицы не соответсвует числу строк второй')

In [10]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
matrix_compication(A, B)

[[4, -11], [12, -3]]

### Часть 2

__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

__Решение:__

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^{2}x + cos^{2}x = 1$


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

__Решение:__

$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 45 - 2 \cdot 0 + 3 \cdot 0 = 180$

    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

__Решение:__

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 \cdot (45-48) - 2 \cdot (36-42) + 3 \cdot (32-35) = -3 + 12 - 9 = 0 $


Проверим с помощью NumPy

In [11]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(np.linalg.det(b))

180.0
180.0


In [12]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(round(np.linalg.det(c)))

0
0


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

$\begin{vmatrix}
3 & 2 \\ 
7 & 6 
\end{vmatrix} = 18 - 14 = 4$

__Решение__:

а) $\begin{vmatrix}
3 & 2 \\ 
7 & 6 
\end{vmatrix} \cdot \begin{vmatrix}
3 & 2 \\ 
7 & 6 
\end{vmatrix} = \begin{vmatrix}
3 \cdot 3 + 2 \cdot 7 & 3 \cdot 2 + 2 \cdot 6 \\ 
7 \cdot 3 + 6 \cdot 7 & 7 \cdot 2 + 6 \cdot 6
\end{vmatrix} = \begin{vmatrix}
23 & 18 \\ 
63 & 50  
\end{vmatrix} = 1150 - 1134 = 16 $

б) $\begin{vmatrix}
3 & 7 \\ 
2 & 6 
\end{vmatrix} = 18 - 14 = 4 $

в) $ 2 \cdot \begin{vmatrix}
3 & 2 \\ 
7 & 6 
\end{vmatrix} = \begin{vmatrix}
6 & 4 \\ 
14 & 12 
\end{vmatrix} = 72-56=16 $

Проверим с помощью NumPy

In [13]:
a = np.array([[3, 2], [7, 6]])
print(f'det(A^2): {np.linalg.det(np.dot(a, a)):.0f}')
print(f'det(A^T): {np.linalg.det(np.transpose(a)):.0f}')
print(f'det(2A): {np.linalg.det(np.dot(2, a)):.0f}')

det(A^2): 16
det(A^T): 4
det(2A): 16
det(A^2): 16
det(A^T): 4
det(2A): 16


__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Решение:__

Матрица называется _сингулярной_ или _вырожденной_, если её определитель равен нулю.

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = -2 \cdot (-14) \cdot 13 + (-3) \cdot 4 \cdot 7 - (-3) \cdot (-14) \cdot (3) - 4 \cdot 7 \cdot 13 = 364 -126 +126 -364 = 0$

In [14]:
a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
round(np.linalg.det(a))

0

0

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

__Решение:__


а) 3 строка является суммой первой и второй строки, следовательно, ее можно отбросить

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1
\end{pmatrix} = $

Таким образом, у нас 2 линейно независимые строки и ранг матрицы равен 2

In [15]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
np.linalg.matrix_rank(a)

2

2

б) 

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

3 строка является суммой первой и второй строки, следовательно, ее можно отбросить

$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$

Таким образом, у нас 3 линейно независимые строки и ранг матрицы равен 3

In [16]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3

3